package org.devoware.table.model;

import static org.devoware.table.dice.Die.*;
import static org.devoware.table.model.FormattedValue.newFormattedValue;
import static org.devoware.table.model.ValueRangeMap.newValueRangeMap;

public class DungeonIdeas {
	
	public static final RandomizableStringSource EXOTIC_LOCATION = newValueRangeMap(D20)
			.with(1, "Among the branches of a tree")
			.with(2, "Around a geyser")
			.with(3, "Behind a waterfall")
			.with(4, "Buried in an avalanche")
			.with(5, "Buried in a sandstorm")
			.with(6, "Buried in volcanic ash")
			.with(7, "Castle or structure sunken in a swamp")
			.with(8, "Castle or structure at the bottom of a sinkhole")
			.with(9, "Floating on the sea")
			.with(10, "In a meteorite")
			.with(11, "On a demiplane or in a pocket dimension")
			.with(12, "In an area devastated by a magical catastrophe")
			.with(13, "On a cloud")
			.with(14, "In the Feywild")
			.with(15, "In the Shadowfell")
			.with(16, "On an island in an underground sea")
			.with(17, "In a volcano")
			.with(18, "On the back of a Gargantuan living creature")
			.with(19, "Sealed inside a magical dome of force")
			.with(20, "Inside a Mordenkainen's magnificent mansion")
			.build();
	
	public static final RandomizableStringSource LOCATION = newValueRangeMap(D100)
			.with(1, 4, "A building in a city")
			.with(5, 8, "Catacombs or sewers beneath a city")
			.with(9, 12, "Beneath a farmhouse")
			.with(13, 16, "Beneath a graveyard")
			.with(17, 22, "Beneath a ruined castle")
			.with(23, 26, "Beneath a ruined city")
			.with(27, 30, "Beneath a temple")
			.with(31, 34, "In a chasm")
			.with(35, 38, "In a cliff face")
			.with(39, 42, "In a desert")
			.with(43, 46, "In a forest")
			.with(47, 50, "In a glacier")
			.with(51, 54, "In a gorge")
			.with(55, 58, "In a jungle")
			.with(59, 62, "In a mountain pass")
			.with(63, 66, "In a swamp")
			.with(67, 70, "Beneath or on top of a mesa")
			.with(71, 74, "In sea caves")
			.with(75, 78, "In several connected mesas")
			.with(79, 82, "On a mountain peak")
			.with(83, 86, "On a promontory")
			.with(87, 90, "On an island")
			.with(91, 95, "Underwater")
			.with(96, 100, EXOTIC_LOCATION)
			.build();

	public static final RandomizableStringSource CULTS_AND_RELIGIOUS_GROUPS = newValueRangeMap(D20)
			.with(1, "Demon-worshipping cult")
			.with(2, "Devil-worshipping cult")
			.with(3, 4, "Elemental Air cult")
			.with(5, 6, "Elemental Earth cult")
			.with(7, 8, "Elemental Fire cult")
			.with(9, 10, "Elemental Water cult")
			.with(11, 15, "Worshippers of an evil deity")
			.with(16, 17, "Worshippers of an good deity")
			.with(18, 20, "Worshippers of an neutral deity")
			.build();
	
	public static final RandomizableStringSource NPC_ALIGNMENT = newValueRangeMap(D20)
			.with(1, 2, "Lawful good")
			.with(3, 4, "Neutral good")
			.with(5, 6, "Chaotic good")
			.with(7, 9, "Lawful neutral")
			.with(10, 11, "Neutral")
			.with(12, "Chaotic neutral")
			.with(13, 15, "Lawful evil")
			.with(16, 18, "Neutral evil")
			.with(19, 20, "Chaotic evil")
			.build();

	public static final RandomizableStringSource NPC_CLASS = newValueRangeMap(D20)
			.with(1, "barbarians")
			.with(2, "bards")
			.with(3, 4, "clerics")
			.with(5, "druids")
			.with(6, 7, "fighters")
			.with(8, "monks")
			.with(9, "paladins")
			.with(10, "rangers")
			.with(11, 14, "rogues")
			.with(15, "sorcerers")
			.with(16, "warlocks")
			.with(17, 20, "wizards")
			.build();

	public static final RandomizableStringSource CREATOR = newValueRangeMap(D20)
			.with(1, "Beholder")
			.with(2, 4, CULTS_AND_RELIGIOUS_GROUPS)
			.with(5, 8, "Dwarves")
			.with(9, "Elves (including drow)")
			.with(10, "Giants")
			.with(11, "Hobgoblins")
			.with(12, 15, newFormattedValue("Humans (%s %s)", NPC_ALIGNMENT, NPC_CLASS))
			.with(16, "Kuo-toa")
			.with(17, "Lich")
			.with(18, "Mind flayers")
			.with(19, "Yuan-ti")
			.with(20, "No creator (natural caverns)")
			.build();

	public static final RandomizableStringSource PURPOSE = newValueRangeMap(D20)
			.with(1, "Death trap")
			.with(2, 5, "Lair")
			.with(6, "Maze")
			.with(7, 9, "Mine")
			.with(10, "Planar gate")
			.with(11, 14, "Stronghold")
			.with(15, 17, "Temple or shrine")
			.with(18, 19, "Tomb")
			.with(20, "Treasure vault")
			.build();

	public static final RandomizableStringSource HISTORY = newValueRangeMap(D20)
			.with(1, 3, "Abandoned by creators")
			.with(4, "Abandoned due to plague")
			.with(5, 8, "Conquered by invaders")
			.with(9, 10, "Creators destroyed by attacking raiders")
			.with(11, "Creators destroyed by discovery made within the site")
			.with(12, "Creators destroyed by internal conflict")
			.with(13, "Creators destroyed by magical catastrophe")
			.with(14, 15, "Creators destroyed by natural disaster")
			.with(16, "Location cursed by the gods and shunned")
			.with(17, 18, "Original creator still in control")
			.with(19, "Overrun by planar creatures")
			.with(20, "Site of a great miracle")
			.build();
}
