package org.devoware.table.model;

import static org.devoware.table.model.ValueSet.newValueSet;

public class Spells {
	

	public static final ValueSet CANTRIPS = newValueSet()
	    .with("Acid Splash")
	    .with("Blade Ward")
	    .with("Chill Touch")
	    .with("Dancing Lights")
	    .with("Druidcraft")
	    .with("Eldritch Blast")
	    .with("Fire Bolt")
	    .with("Friends")
	    .with("Guidance")
	    .with("Light")
	    .with("Mage Hand")
	    .with("Mending")
	    .with("Message")
	    .with("Minor Illusion")
	    .with("Poison Spray")
	    .with("Prestidigitation")
	    .with("Produce Flame")
	    .with("Ray of Frost")
	    .with("Resistance")
	    .with("Sacred Flame")
	    .with("Shillelagh")
	    .with("Shocking Grasp")
	    .with("Spare the Dying")
	    .with("Thaumaturgy")
	    .with("Thorn Whip")
	    .with("True Strike")
	    .with("Vicious Mockery")
	    .build();
	
	public static final ValueSet LEVEL_1_SPELLS = newValueSet()
	    .with("Alarm")
	    .with("Animal Friendship")
	    .with("Armor of Agathys")
	    .with("Arms of Hadar")
	    .with("Bane")
	    .with("Bless")
	    .with("Burning Hands")
	    .with("Charm Person")
	    .with("Chromatic Orb")
	    .with("Color Spray")
	    .with("Command")
	    .with("Compelled Duel")
	    .with("Comprehend Languages")
	    .with("Create or Destroy Water")
	    .with("Cure Wounds")
	    .with("Detect Evil and Good")
	    .with("Detect Magic")
	    .with("Detect Poison and Disease")
	    .with("Disguise Self")
	    .with("Dissonant Whispers")
	    .with("Divine Favor")
	    .with("Ensnaring Strike")
	    .with("Entangle")
	    .with("Expeditious Retreat")
	    .with("Faerie Fire")
	    .with("False Life")
	    .with("Feather Fall")
	    .with("Find Familiar")
	    .with("Fog Cloud")
	    .with("Goodberry")
	    .with("Grease")
	    .with("Guiding Bolt")
	    .with("Hail of Thorns")
	    .with("Healing Word")
	    .with("Hellish Rebuke")
	    .with("Heroism")
	    .with("Hex")
	    .with("Hunter's Mark")
	    .with("Identify")
	    .with("Illusory Script")
	    .with("Inflict Wounds")
	    .with("Jump")
	    .with("Longstrider")
	    .with("Mage Armor")
	    .with("Magic Missile")
	    .with("Protection from Evil and Good")
	    .with("Purify Food and Drink")
	    .with("Ray of Sickness")
	    .with("Sanctuary")
	    .with("Searing Smite")
	    .with("Shield")
	    .with("Shield of Faith")
	    .with("Silent Image")
	    .with("Sleep")
	    .with("Speak with Animals")
	    .with("Tasha's Hideous Laughter")
	    .with("Tenser's Floating Disk")
	    .with("Thunderous Smite")
	    .with("Thunderwave")
	    .with("Unseen Servant")
	    .with("Witch Bolt")
	    .with("Wrathful Smite")
	    .build();
	
	public static final ValueSet LEVEL_2_SPELLS = newValueSet()
	    .with("Aid")
	    .with("Alter Self")
	    .with("Animal Messenger")
	    .with("Arcane Lock")
	    .with("Augury")
	    .with("Barkskin")
	    .with("Beast Sense")
	    .with("Blindness/Deafness")
	    .with("Blur")
	    .with("Branding Smite")
	    .with("Calm Emotions")
	    .with("Cloud of Daggers")
	    .with("Continual Flame")
	    .with("Cordon of Arrows")
	    .with("Crown of Madness")
	    .with("Darkness")
	    .with("Darkvision")
	    .with("Detect Thoughts")
	    .with("Enhance Ability")
	    .with("Enlarge/Reduce")
	    .with("Enthrall")
	    .with("Find Steed")
	    .with("Find Traps")
	    .with("Flame Blade")
	    .with("Flaming Sphere")
	    .with("Gentle Repose")
	    .with("Gust of Wind")
	    .with("Hallow")
	    .with("Heat Metal")
	    .with("Hold Person")
	    .with("Invisibility")
	    .with("Knock")
	    .with("Lesser Restoration")
	    .with("Levitate")
	    .with("Locate Animals or Plants")
	    .with("Locate Object")
	    .with("Magic Mouth")
	    .with("Magic Weapon")
	    .with("Melf's Acid Arrow")
	    .with("Mirror Image")
	    .with("Misty Step")
	    .with("Moonbeam")
	    .with("Nystul's Magic Aura")
	    .with("Pass without Trace")
	    .with("Phantasmal Force")
	    .with("Prayer of Healing")
	    .with("Protection from Poison")
	    .with("Ray of Enfeeblement")
	    .with("Rope Trick")
	    .with("Scorching Ray")
	    .with("See invisibility")
	    .with("Shatter")
	    .with("Silence")
	    .with("Spider Climb")
	    .with("Spike Growth")
	    .with("Spiritual Weapon")
	    .with("Suggestion")
	    .with("Warding Bond")
	    .with("Web")
	    .with("Zone of Truth")
	    .build();
	
	public static final ValueSet LEVEL_3_SPELLS = newValueSet()
	    .with("Animate Dead")
	    .with("Aura of Vitality")
	    .with("Beacon of Hope")
	    .with("Bestow Curse")
	    .with("Blinding Smite")
	    .with("Blink")
	    .with("Call Lightning")
	    .with("Clairvoyance")
	    .with("Conjure Animals")
	    .with("Conjure Barrage")
	    .with("Counterspell")
	    .with("Create Food and Water")
	    .with("Crusader's Mantle")
	    .with("Daylight")
	    .with("Dispel Magic")
	    .with("Elemental Weapon")
	    .with("Fear")
	    .with("Feign Death")
	    .with("Fireball")
	    .with("Fly")
	    .with("Gaseous Form")
	    .with("Glyph of Warding")
	    .with("Haste")
	    .with("Hunger of Hadar")
	    .with("Hypnotic Pattern")
	    .with("Leomund's Tiny Hut")
	    .with("Lightning Arrow")
	    .with("Lightning Bolt")
	    .with("Magic Circle")
	    .with("Major Image")
	    .with("Mass Healing Word")
	    .with("Meld Into Stone")
	    .with("Nondetection")
	    .with("Phantom Steed")
	    .with("Plant Growth")
	    .with("Protection from Energy")
	    .with("Remove Curse")
	    .with("Revivify")
	    .with("Sending")
	    .with("Sleet Storm")
	    .with("Slow")
	    .with("Speak with Dead")
	    .with("Speak with Plants")
	    .with("Spirit Guardians")
	    .with("Stinking Cloud")
	    .with("Tongues")
	    .with("Vampiric Touch")
	    .with("Water Breathing")
	    .with("Water Walk")
	    .with("Wind Wall")
	    .build();
	
	public static final ValueSet LEVEL_4_SPELLS = newValueSet()
	    .with("Arcane Eye")
	    .with("Aura of Life")
	    .with("Aura of Purity")
	    .with("Banishment")
	    .with("Blight")
	    .with("Compulsion")
	    .with("Confusion")
	    .with("Conjure Minor Elementals")
	    .with("Conjure Woodland Beings")
	    .with("Control Water")
	    .with("Death Ward")
	    .with("Dimension Door")
	    .with("Divination")
	    .with("Dominate Beast")
	    .with("Evard's Black Tentacles")
	    .with("Fabricate")
	    .with("Fire Shield")
	    .with("Freedom of Movement")
	    .with("Giant Insect")
	    .with("Grasping Vine")
	    .with("Greater Invisibility")
	    .with("Guardian of Faith")
	    .with("Hallucinatory Terrain")
	    .with("Ice Storm")
	    .with("Leomund's Secret Chest")
	    .with("Locate Creature")
	    .with("Mordenkainen's Faithful Hound")
	    .with("Mordenkainen's Private Sanctum")
	    .with("Otiluke's Resilient Sphere")
	    .with("Phantasmal Killer")
	    .with("Polymorph")
	    .with("Staggering Smite")
	    .with("Stone Shape")
	    .with("Stoneskin")
	    .with("Wall of Fire")
	    .build();
	
	public static final ValueSet LEVEL_5_SPELLS = newValueSet()
	    .with("Animate Objects")
	    .with("Antilife Shell")
	    .with("Awaken")
	    .with("Banishing Smite")
	    .with("Bigby's Hand")
	    .with("Circle of Power")
	    .with("Commune")
	    .with("Commune with Nature")
	    .with("Cone of Cold")
	    .with("Conjure Elemental")
	    .with("Conjure Volley")
	    .with("Contact Other Plane")
	    .with("Contagion")
	    .with("Creation")
	    .with("Destructive Wave")
	    .with("Dispel Evil and Good")
	    .with("Dominate Person")
	    .with("Dream")
	    .with("Flame Strike")
	    .with("Geas")
	    .with("Greater Restoration")
	    .with("Hold Monster")
	    .with("Insect Plague")
	    .with("Legend Lore")
	    .with("Mass Cure Wounds")
	    .with("Mislead")
	    .with("Modify Memory")
	    .with("Passwall")
	    .with("Planar Binding")
	    .with("Raise Dead")
	    .with("Rary's Telepathic Bond")
	    .with("Reincarnate")
	    .with("Scrying")
	    .with("Seeming")
	    .with("Swift Quiver")
	    .with("Telekinesis")
	    .with("Teleportation Circle")
	    .with("Tree Stride")
	    .with("Wall of Force")
	    .with("Wall of Stone")
	    .build();
	
	public static final ValueSet LEVEL_6_SPELLS = newValueSet()
	    .with("Arcane Gate")
	    .with("Blade Barrier")
	    .with("Chain Lightning")
	    .with("Circle of Death")
	    .with("Conjure Fey")
	    .with("Contingency")
	    .with("Create Undead")
	    .with("Disintegrate")
	    .with("Drawmij's Instant Summons")
	    .with("Eyebite")
	    .with("Find the Path")
	    .with("Flesh to Stone")
	    .with("Forbiddance")
	    .with("Globe of Invulnerability")
	    .with("Guards and Wards")
	    .with("Harm")
	    .with("Heal")
	    .with("Heroes' Feast")
	    .with("Magic Jar")
	    .with("Mass Suggestion")
	    .with("Move Earth")
	    .with("Otilike's Freezing Sphere")
	    .with("Otto's Irresistible Dance")
	    .with("Planar Ally")
	    .with("Programmed Illusion")
	    .with("Sunbeam")
	    .with("Transport via Plants")
	    .with("True Seeing")
	    .with("Wall of Ice")
	    .with("Wall of Thorns")
	    .with("Wind Walk")
	    .with("Word of Recall")
	    .build();
	
	public static final ValueSet LEVEL_7_SPELLS = newValueSet()
	    .with("Conjure Celestial")
	    .with("Delayed Blast Fireball")
	    .with("Divine Word")
	    .with("Etherealness")
	    .with("Finger of Death")
	    .with("Fire Storm")
	    .with("Forcecage")
	    .with("Mirage Arcane")
	    .with("Mordenkainen's Magnificent Mansion")
	    .with("Mordenkainen's Sword")
	    .with("Plane Shift")
	    .with("Prismatic Spray")
	    .with("Project Image")
	    .with("Regenerate")
	    .with("Resurrection")
	    .with("Reverse Gravity")
	    .with("Sequester")
	    .with("Simulacrum")
	    .with("Symbol")
	    .with("Teleport")
	    .build();
	
	public static final ValueSet LEVEL_8_SPELLS = newValueSet()
	    .with("Animal Shapes")
	    .with("Antimagic Field")
	    .with("Antipathy/Sympathy")
	    .with("Clone")
	    .with("Cloudkill")
	    .with("Control Weather")
	    .with("Demiplane")
	    .with("Dominate Monster")
	    .with("Earthquake")
	    .with("Feeblemind")
	    .with("Glibness")
	    .with("Holy Aura")
	    .with("Incendiary Cloud")
	    .with("Maze")
	    .with("Mind Blank")
	    .with("Power Word Stun")
	    .with("Sunburst")
	    .with("Telepathy")
	    .with("Tsunami")
	    .build();
	
	public static final ValueSet LEVEL_9_SPELLS = newValueSet()
	    .with("Astral Projection")
	    .with("Foresight")
	    .with("Gate")
	    .with("Imprisonment")
	    .with("Mass Heal")
	    .with("Meteor Swarm")
	    .with("Power Word Heal")
	    .with("Power Word Kill")
	    .with("Prismatic Wall")
	    .with("Shapechange")
	    .with("Storm of Vengeance")
	    .with("Time Stop")
	    .with("True Polymorph")
	    .with("True Resurrection")
	    .with("Weird")
	    .with("Wish")
	    .build();

}
