package org.devoware.table.model;

import static org.devoware.table.dice.Die.*;
import static org.devoware.table.model.ValueRangeMap.newValueRangeMap;

public class Settlements {
	public static final RandomizableStringSource RACE_RELATIONS = newValueRangeMap(D20)
			.with(1, 10, "Harmony")
			.with(11, 14, "Tension or rivalry")
			.with(15, 16, "Racial majority are conquerors")
			.with(17, "Racial minority are rulers")
			.with(18, "Racial minority are refugees")
			.with(19, "Racial majority oppresses minority")
			.with(20, "Racial minority oppresses majority")
			.build();
	
	public static final RandomizableStringSource RULERS_STATUS = newValueRangeMap(D20)
			.with(1, 5, "Respected, fair, and just")
			.with(6, 8, "Feared tyrant")
			.with(9, "Weakling manipulated by others")
			.with(10, "Illegitimate ruler, simmering civil war")
			.with(11, "Ruled or controlled by a powerful monster")
			.with(12, "Mysterious, anonymous cabal")
			.with(13, "Contested leadership, open fighting")
			.with(14, "Cabal seized power openly")
			.with(15, "Doltish lout")
			.with(16, "On a deathbed, claimants compete for power")
			.with(17, 18, "Iron-willed but respected")
			.with(19, 20, "Religious leader")
			.build();

	public static final RandomizableStringSource NOTABLE_TRAITS = newValueRangeMap(D20)
			.with(1, "Canals in place of streets")
			.with(2, "Massive statue or monument")
			.with(3, "Grand temple")
			.with(4, "Large fortress")
			.with(5, "Verdant parks and orchards")
			.with(6, "River divides town")
			.with(7, "Major trade center")
			.with(8, "Headquarters of a powerful family or guild")
			.with(9, "Population mostly wealthy")
			.with(10, "Destitute, rundown")
			.with(11, "Awful smell (tanneries, open sewers)")
			.with(12, "Center of trade for one specific good")
			.with(13, "Site of many battles")
			.with(14, "Site of a mythic or magical event")
			.with(15, "Important library or archive")
			.with(16, "Worship of all gods banned")
			.with(17, "Sinister reputation")
			.with(18, "Notable library or academy")
			.with(19, "Site of important tomb or graveyard")
			.with(20, "Built atop ancient ruins")
			.build();

	public static final RandomizableStringSource KNOWN_FOR_ITS = newValueRangeMap(D20)
			.with(1, "Delicious cuisine")
			.with(2, "Rude people")
			.with(3, "Greedy merchants")
			.with(4, "Artists and writers")
			.with(5, "Great hero/savior")
			.with(6, "Flowers")
			.with(7, "Hordes of beggars")
			.with(8, "Tough warriors")
			.with(9, "Dark magic")
			.with(10, "Decadence")
			.with(11, "Piety")
			.with(12, "Gambling")
			.with(13, "Godlessness")
			.with(14, "Education")
			.with(15, "Wines")
			.with(16, "High fashion")
			.with(17, "Political intrigue")
			.with(18, "Powerful guilds")
			.with(19, "Strong drink")
			.with(20, "Patriotism")
			.build();

	public static final RandomizableStringSource CURRENT_CALAMITY = newValueRangeMap(D20)
			.with(1, "Suspected vampire infestation")
			.with(2, "New cult seeks converts")
			.with(3, "Important figure died (murder suspected)")
			.with(4, "War between rival thieves' guilds")
			.with(5, 6, "Plague or famine (sparks riots)")
			.with(7, "Corrupt officials")
			.with(8, 9, "Marauding monsters")
			.with(10, "Powerful wizard has moved into town")
			.with(11, "Economic depression (trade disrupted)")
			.with(12, "Flooding")
			.with(13, "Undead stirring in cemetaries")
			.with(14, "Prophecy of doom")
			.with(15, "Brink of war")
			.with(16, "Internal strife (leads to anarchy)")
			.with(17, "Besieged by enemies")
			.with(18, "Scandal threatens powerful families")
			.with(19, "Dungeon discovered (adventurers flock to town)")
			.with(20, "Religious sects struggle for power")
			.build();
}
